### ISSUE TITLE
Stared icon is misleading

### ISSUE THREAD

**Issue by bradtaniguchi** [CaraLagumen/baristabook#5]
When staring an item the start goes "hollow", which is the opposite of what I'd expect most of the time. Usually something is selected/stared the "checkbox" is filled. Maybe we should flip the icon being filled/not-filled for starred items?

This is the current **unselected** icon
![image](https://user-images.githubusercontent.com/10079147/79052973-dc7f8900-7bee-11ea-9d7e-21bba44e7060.png)

This is the current **selected** icon
![image](https://user-images.githubusercontent.com/10079147/79053018-ffaa3880-7bee-11ea-88e1-be07f60499cb.png)

**Comment by CaraLagumen** [comment]
Hey Brad, I added more clarity for the starred buttons! Thank you for starting this issue.

![xxx](https://user-images.githubusercontent.com/45896071/84338567-4534a480-ab51-11ea-8702-0f31ea4055e3.gif)

Fixed in commit [f5664d4939a04c3aac5900d26e1483acafc81c66](https://github.com/CaraLagumen/baristabook/commit/f5664d4939a04c3aac5900d26e1483acafc81c66).
